### ISSUE TITLE
Jakarta Persistence Entity Model Snippet

### ISSUE THREAD

**Issue by AnkushSharma2698** [MicroShed/jakarta-ls#35]
Example of using JPA in open liberty to create a model: https://github.com/OpenLiberty/guide-jpa-intro/blob/master/finish/backendServices/src/main/java/io/openliberty/guides/event/models/Event.java

Make a generic version of this...

**Comment by kathrynkodama** [comment]
Not sure if we will need a snippet for this - from what I can tell there is no popular use case of an Entity Model.  I imagine our snippet would be a class with `@Entity` denoted which may not be that useful to developers. 

Let's discuss here if you are picturing a more complete snippet.

**Comment by AnkushSharma2698** [comment]
For this one I was thinking at a minimum it would be a simple entitymodel snippet utilizing the most basic functionality. Something I have found useful during programming is a snippet of quick boilerplate code, so I will show what I mean:

```ruby
package ${1:packagename};

/* Include all of the imports in the snippet */
import javax.persistence.Entity; // Looks like this is still part of javax rather than jakarta package, according to jakarta docs
import javax.persistence.Table;
import javax.persistence.NamedQuery;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.GenerationType;

@Entity
@Table(name = ${2: tableName})
@NamedQuery()
public class ${3:entityName} {
  private static final long serialVersionUID = 1L;
   /* Majority of models will use an ID */
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Id
  @Column(name="${4:idName}")
  private int id;

  /* One Example Column provided */
  @Column(name="exampleCol"
  private String exampleCol;

  /* Sample Getters and Setters */
  public int getId() {
        return id;
    }

  public void setId(int id) {
        this.id = id;
  }

  public int getexampleCol() {
        return exampleCol;
  }

  public void setexampleCol(String example) {
        this.exampleCol = example;
  }
}

````

Generally a lot of Models implement Serializable but to simplify the snippet to provide barebones boilerplate I do believe this provides value

**Comment by AnkushSharma2698** [comment]
There is also another snippet related to the type of fetching that can be done on a column of an entity.
The default form is Eager fetching

```ruby
@Basic
protected String name
```

```ruby
@Basic(fetch=LAZY) /* Lazy loading from the database*/
protected String name
```

```ruby
@Basic(fetch=EAGER) /* This is the default so maybe not needed*/
protected String name
```

**Comment by kathrynkodama** [comment]
I see what you mean, this could be useful to developers.  Not sure that we need to provide the snippets for fetching since they are pretty minimal.

A few notes for the entity model snippet:
- In terms of the namespace, with the release of Jakarta EE 9 the namespace will change from `javax` to `jakarta` see: https://jakarta.ee/specifications/persistence/3.0/apidocs/jakarta.persistence/jakarta/persistence/Entity.html
- The `@NamedQuery` annotation requires a name and query
- an entity class must have a no-arg constructor

**Comment by AnkushSharma2698** [comment]
Oh Nice!! I couldn't find the newest docs, so this is a big help! And I will update the snippets
