### ISSUE TITLE
Jakarta Persistence Persistence Context Snippet

### ISSUE THREAD

**Issue by AnkushSharma2698** [MicroShed/jakarta-ls#36]
Generic Snippet to display how to create a Data access object to interact with a model.
https://github.com/OpenLiberty/guide-jpa-intro/blob/master/finish/backendServices/src/main/java/io/openliberty/guides/event/dao/EventDao.java

Depicts usage of a EntityManager

**Comment by kathrynkodama** [comment]
What did you have in mind for this snippet? 
We could have a snippet for the `@PersistenceContext` annotation:

```java
@PersistenceContext(name="")
```

Since the default value for the type field is TRANSACTION we could have and extended persistence context:
```java
@PersistenceContext(type=PersistenceContextType.EXTENDED)
```

Similarly since the default value for the synchronization field is SYNCHRONIZED, we could have both an extended and unsynchronized persistence context, which seems like a common use case:
```java
@PersistenceContext(type=PersistenceContextType.EXTENDED, synchronization = SynchronizationType.UNSYNCHRONIZED)
```

**Comment by AnkushSharma2698** [comment]
I really like this idea! Also the idea I had was regarding a larger snippet representing what a DAO is.
As I have been looking at DAO examples, I noticed that the general use case was to create a ```CRUD``` interaction file with a given entity. So I was thinking to create a general ```persistcrud``` or ```persistdao``` snippet that implements a very simple Create, Read, Update, and Delete method for a Dao. This snippet would involve an `EntityManager` as well as a ```persistenceContext```.

Minimal Example -  This would be very very fast to implement providing a CRUD interface for a model immediately:

```java
package ${1:packagename};

import java.util.List;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;

import ${2:pathToModel};

import jakarta.enterprise.context.RequestScoped;

@RequestScoped
class ${3:modelName}DAO {
    /* Create Persistence Context */
    @PersistenceContext(name = "jpa-unit")
    private EntityManager em;

   /* CREATE */
   public void create${3:modelName}(${3:modelName} obj) {
       em.persist(obj);
   }

   /* READ */
   public ${3:modelName} read${3:modelName}(int modelID) {
        return em.find(${3:modelName}.class, modelID);
   }

  /* READ ALL*/
  public List<${3:modelName}> readAll${3:modelName}s() {
      return em.createNamedQuery("${3:modelName}.findAll", ${3:modelName}.class).getResultList();
  }

   /*UPDATE */
   public void update${3:modelName}(${3:modelName} obj) {
       em.merge(obj);
   }

   /*DELETE*/
   public void delete${3:modelName}(${3:modelName} obj) {
       em.delete(obj);
   }
}

```

**Comment by AnkushSharma2698** [comment]
I definitely think the persistenceContext snippets should be included as well as provided the multiple options easily would be very useful

**Comment by kathrynkodama** [comment]
The concern I have with the DAO snippet is that it requires the model to already exist. I don't think we can assume that for a snippet.
