### ISSUE TITLE
Jakarta Persistence Query Snippets

### ISSUE THREAD

**Issue by AnkushSharma2698** [MicroShed/jakarta-ls#39]
Create Native Query (https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#returning-managed-entities-from-native-queries)

This is an inline query that can be built using an EntityManager

**Comment by AnkushSharma2698** [comment]
There are several different types of queries in Jakarta Persistence, to create a snippet to streamline query creation would be really nice in my opinion.

I have not differentiated between getting a single result or multiple results from a query because that is implementation dependent.

Basic Query: `pquery`
```java
/* em is EntityManager */
Query q = em.createQuery("SELECT ${1:fields} FROM ${2:entityModel} WHERE ${3:conditions}");
```

TypedQuery: `ptypequery` (The preferred query type when the return type is known)
```java
/* em is EntityManager */
TypedQuery<${1:returnType}> typedQuery = em.createQuery("SELECT ${2:fields} FROM ${1:entityModel} WHERE ${3:conditions}", ${1:returnType}.class);
```

NamedQuery: `pnamedquery`
```java
/* Add This annotation right above the entity class definition */
@NamedQuery(name = "${1:entityModel}.${2:queryName}", query = "${3:queryDefinition}")
/* Named Query usage...em is EntityManager */
Query namedQuery = em.createNamedQuery("${1:entityModel}.${2:queryName}");
/* If query requires parameters, ensure that those are set */
```

NativeQuery: `pnativequery` (simple SQL query that is not restrict by JPQL syntax)
```java
/* em is EntityManager */
Query nativeQuery = em.createNativeQuery("${1:queryDefinition}", ${2:entityModel});
```

These snippets are all created for a user that wants to use raw SQL syntax. A preferred method is to use the Criteria API to build queries programatically, but that is not as easily generalized.

**Comment by kathrynkodama** [comment]
Based on the amount of placeholder text and potential variation of queries, it doesn't seem like these snippets would add a lot of value to a developer. If you have other ideas let me know.
