### ISSUE TITLE
Run Diagnostics on the relevant Annotations for Persistence

### ISSUE THREAD

**Issue by AnkushSharma2698** [MicroShed/jakarta-ls#40]
Ensure that when Persistence Annotations are used in files, these a Persistence Diagnostic Collector is ran and checks for the correct imports and that persistence is in class path so it is even usable.

**Comment by kathrynkodama** [comment]
This is a very generic issue. We should open individual issues for each of the diagnostics (similar to how we did for Servlet)

**Comment by AnkushSharma2698** [comment]
There is not many use cases where users are extending a class and that I must check for the existence of some extending class in the class def. Rather I believe the diagnostics I will need on annotations will be related to imports.

So I will be creating Annotation diagnostics for the following:

```java
@Entity
@NamedQuery
@PersistenceContext
@Table
@Column
@Id
```

So the idea is that I will perform a diagnostic checking first for the ```jakarta.persistence.*``` import. But if that is not present then I will search more granularly for annotation specific imports.

Once we have decided if these are worth doing then I can open up more detailed issues individually.

**Comment by kathrynkodama** [comment]
I don't think it's necessary that we implement our own diagnostics for correcting the imports as the Java Language Server already offers this capability
