### ISSUE TITLE
Jakarta Persistence Snippet - Annotation snippets for the many types of Column Relationships

### ISSUE THREAD

**Issue by AnkushSharma2698** [MicroShed/jakarta-ls#41]
There are Several different types of relationships columns in different tables can have. This is represented through annotations in Jakarta Persistence. These annotations also have several optional parameters that yield different behaviour
I will provide and example of a single instance using the `@OneToOne` annotation.

```java
@OneToOne() // Basic Usage
@OneToOne(optional=false) // A non-null relationship must always exist
@OneToOne(cascade=REMOVE) // cascades the remove option to the target
... etc.
```
There are several other parameters that can be placed to provide snippets,
this is a relatively small amount of code so I am not sure if it is the most viable.
But it can be made viable with associated comments in the snippet to provide the user context into what the snippet does.

**Comment by kathrynkodama** [comment]
I don't think we need to include these snippets. If a user wants more information on what an annotation does, usually they would hover over the annotation to see the javadoc.
