### ISSUE TITLE
Jakarta Bean Validation @Email Snippet

### ISSUE THREAD

**Issue by rezaakv** [MicroShed/jakarta-ls#51]
Add snippet for Jakarta Bean Validation built-in @Email constraint annotation: 
```
@Email
private String emailAddress;
```
[https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#builtinconstraints-email](https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#builtinconstraints-email)

**Comment by kathrynkodama** [comment]
Let's open up similar snippet issues for other popular constraint annotations
