### ISSUE TITLE
Jakarta Bean Validation ConstraintValidator snippet

### ISSUE THREAD

**Issue by kathrynkodama** [MicroShed/jakarta-ls#56]
Snippet for a custom constraint validator class:
```
package {};

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

public class {} implements ConstraintValidator<A extends Annotation, Object> {

    @Override
    public boolean isValid(Object arg0, ConstraintValidatorContext constraintContext) {

    }

}
```

@rezaakv can you evaluate if this would be useful to developers, and if perhaps we should provide a snippet for a popular annotation type?

**Comment by AnkushSharma2698** [comment]
I am not sure how useful of a snippet this is. The reason being is that for this snippet to work, the user needs to be aware that they must have created an Annotation, and I am not sure that we want to have an exterior dependency like that on a snippet. If keeping the Annotation part is not an issue then I think this would be a good snippet, but I would be open to discussion on this one.

If we create a Validator snippet I think an Annotation one should accompany it, but once again, I am not sure how well we can encompass this use case generically.

**Comment by kathrynkodama** [comment]
Thank you @AnkushSharma2698, closing for now.
