### ISSUE TITLE
quick fix(s) for general servlet

### ISSUE THREAD

**Issue by PENGYUXIONG** [MicroShed/jakarta-ls#61]
add quick fixes for existing diagnostics inside servlet
- quick fix(s) for implementing each of the interfaces (Done)
- quick fix for correcting the annotations
- quick fix for implementing Filter (Done)

**Comment by kathrynkodama** [comment]
Start with:
- adding a quick fix to this diagnostic: https://github.com/MicroShed/jakarta-ls/issues/13 for implementing the Filter interface.
- adding multiple quick fixes for each of the possible interfaces that must be implemented: https://github.com/MicroShed/jakarta-ls/issues/6

Leave the quick fix for correcting the annotations to the end, as it will require some different logic from the quick fix we have right now.

**Comment by kathrynkodama** [comment]
Outstanding: quick fix for correcting the attributes on the `@WebServlet` and `@WebFilter` annotationsm see https://github.com/MicroShed/jakarta-ls/issues/8

**Comment by kathrynkodama** [comment]
Fixed with #73
